apiVersion: v1
data:
    password: ENC[AES256_GCM,data:CatZIG6CfKW+MHtrh2igAZgtC+Dnw/WJR1JTpnZtPBCNsvbrVgqTbxLm4qI=,iv:8lfg0vFj9bbF7KTAXCQMkgtxBKIQFge4uf0qYbzQE1A=,tag:HFstq2eYHZm9dHEf9aPnDA==,type:str]
    username: ENC[AES256_GCM,data:jZfC619fnUhK4NHj,iv:PpUIIP+K5tOkn8yYIAzh+p2C2IRLM08xAUCBu4zDjIg=,tag:m2cH8otXMWEEVuVaa7/3HA==,type:str]
kind: Secret
metadata:
    name: cnpg-linkding-auth
    namespace: linkding
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOWkzcWxlWDgyc24wQmhy
            QVdIaDlkaW1oWmRGalBlZE5jelhwTHR0T0JnCnlOaGJpLzJ3YXBTc213OEd0Qis1
            RFVqNkFpSDZvNDhsSHZvU2pTNXVpNlkKLS0tIGZYcTF5dWJnd0RnQWhqNlY4U0Mr
            TTlSMzFJMHhsMFUrTTluTmhLUjBFQXMKe76qjy/kuEF6ZqsqEX2tsfPGoYlwywFB
            mfFjVV8CcuPG6T4qusnmjdhTZnodY+6ykf+FsiFcyVLFj4ScZdYk1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T00:23:28Z"
    mac: ENC[AES256_GCM,data:jFf5ma6Ress2nqiDc1x240Npv4KfkeedJpjuKNNt9tgNczr0tXkZPnhcGrPRoQmh+StMu1/WLiRZa4n04JHK3iPTO3dRcHXVu+IX7v2eLromqyRU8yTS0T1YoyT8WAZjzRp29UKHLP+5Kfq/K6szqVZeDAP6Ag4F84ji4O5YM2U=,iv:Id7y54XIoERzaLLQVBjKQojeoKyzswDmNF34RoBkloY=,tag:2aOobMx0+XrA5UlTuHo+2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
