apiVersion: v1
data:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:Aex2dJ7Jbo8=,iv:5jcFRAZQc1hh9vprGPCAPWOZNwibPZLY9q4r92+m5uI=,tag:amk5kHHDwDAT68Rg2K7CSg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:J4oKXXzHNCok1PsdFQ6oOZfz/e56ReNjdVncnhD4mGwCFIVGFNJ+VJqDHGs=,iv:RP8ofC8HpOtSQG9YSpmzK4P8SiItU/s8+QjRumP8F+Q=,tag:gysVLRbcB033L3hVMtUcVw==,type:str]
kind: Secret
metadata:
    name: minio-creds-cnpg
    namespace: cnpg-system
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByV3UvcEJNS0dwRWt2L3E5
            aDlqbUhhSEI4RW1DSzlwTDlidVNrZ2pGL3pFCnI0cnhuaXRkSTNleFUzYWZsT2RN
            WmhqL01KMzBIekNkNmhGbHBLSHFzeGsKLS0tIDhEOGFIMEkvc0QzMzYyUndwUE1h
            SzJLSDA0cjR2MDNqdEgzeS8vd0NzQ3cK/KtWT2vCiHDQs3UpEmgKWu7/ckTcrRGk
            5c1VYGZshFIAl1uasQNbLxZLZyoJLnYSVfLf+p/RB+FcNT28LnfJwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T00:01:18Z"
    mac: ENC[AES256_GCM,data:fcOFgRPvCEQMPJRUY5KmLfQfh68yYChvE1+EMHMJZyU5xd/b3jmBsws2l/guvMHoWIQ6qv+svR9WcElQ+8SXUFuSkbr5ADFaVUmQiGHOKrWgkg6S53MG10/RtGqcUBGv1bmTqEqWi+SFXjAwEMmmrSIjrsOqLdK7t3bwZjxivy8=,iv:oTbwkwEFDavVeay3yuEwytBF4qy0faoXElRpd/SySk8=,tag:lZIoLQkuKnOXQGVBk0TV+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
