apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Ug3CLViGE6Fn/+GFOyNc8UaXO0ogrs22fKUqccqMDUdAvQxY+mbhYqILIHk=,iv:oH2sJcBe/he2Ajh10G6+uegW2ndVz0RZ3DREiwJHZGg=,tag:+w6500YvbLtO0E5Vx+HWwQ==,type:str]
    username: ENC[AES256_GCM,data:L3vJo/mvLqw=,iv:/w1YkMYSqNLZiImwSNAc32h4dhRwS7qjQelc1u4+k5k=,tag:WCItMKNeO88Am4Niu1xDYQ==,type:str]
kind: Secret
metadata:
    name: mariadb-cluster-auth
    namespace: mariadb-system
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdnVGWWVCYUhTbllkUUN5
            ME5kdDFoTWp3K3hHWkJsT1J5SDZmMUVSRUN3CndEY2E3cWg5K0FxMXJWUUUzZGcy
            UzBtS3JvSk1CeGhWZUNKTkVndnJ3aVkKLS0tIGhMbTFySTNOVlBXLzBqcmFhVmJk
            MWIvN1A4WWgyZVM2V3p4SjQ3QTQrbG8KDJbcpjHVpB3jwIGUuNWmPi2FZvV0H5Os
            WrjSOoxSUBwEQ+wpy1RJWCwP03slnPKb0bKxL2ExCIrBlNMPt0YQ8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T17:44:07Z"
    mac: ENC[AES256_GCM,data:jhzcQAhEOFgDq7rLsKumlN941/cedAlPTUCQe0Roh3U+PwaC4nOJG0vCFPIBqO+w/cMXwVANOftChOsPWldGvhc6H1EV/ALGPOQRHxVk5jHAGwMY6UkEhyhcQOKmIILlQqzEiMSwKRiLOvYnXBzOIEUmPMgQnoEHiQCZNGmNxqo=,iv:LOc68+TXeMcmExCfOpjxuIDIw4waKKUb22Ex/d7ZqO8=,tag:6UukqqnYQQDtd2GxFqML+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
