---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: openwebui-cnpg
  namespace: cnpg-system
spec:
  name: openwebui
  owner: openwebui
  databaseReclaimPolicy: retain
  cluster:
    name: cnpg-cluster
  extensions:
    - name: vector
      version: '0.8.2'
