---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crd
  namespace: mariadb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadb-operator-crds
      version: 25.10.4 # {"$imagepolicy": "flux-system:mariadb-operator:tag"}
      sourceRef:
        kind: HelmRepository
        name: mariadb
        namespace: mariadb-system
      interval: 1m
  values:
