apiVersion: v1
data:
    api_token: ENC[AES256_GCM,data:jaok0Ox3i0pZyPkR1N5NNmEPJYwcn+lF602JLnzB5wCsz82zJBzj+q4Znq8hKOqIQUgPM/4rmcA=,iv:KoDjQY1RDjCR1rdyx5WXQJrZZc2HDYMzIghsDulKHOE=,tag:+asMB2dBKADqYGpLQaRBwQ==,type:str]
kind: Secret
metadata:
    name: njalla-secrets
    namespace: cert-manager
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWDkyNUV3WjgyeHpVRFU3
            WUVZNndEYkpzVDFZMXJuamFud25MdzRRT0FRCnRja0pqUlV1ZHltRzRPbUdHMFJv
            ODJYbEJ4TXgwWDVZZEREUThpTFMxcTgKLS0tIFVkZW5wem9MeFdKaXY5YmR4UVVE
            U1hlQXdVZnQ2YysvTW1HVWNHV2h3TTAKE5qwAWBBg3wVsglv31PWJk7xfByd6709
            LcJ2Cxs28gl+KY2+0AZ/2SuFcCzUXsV7DPPYLy/YoTL+9H0tuASD7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T18:52:44Z"
    mac: ENC[AES256_GCM,data:qtg55ohrJ+GaCBHD7gA05O7Zsw4rFERbjejLt6VjFcTHRV0g+vDPXquSsGUvK94TLCmw3vYIvdH1t5C1KWvemrovIsdyrxgMznNC4tIuLP7c603BI2zendQMzejKgCbJpMeH4+sc6EbefOuFuib/SlREI/l9LmURhs8LXtPnrmI=,iv:PNha0E7RTBsZu3DtoFQnRNCVTr8uBPq+OLlyHgosHYM=,tag:dR+nKcz0WOneK78GrSdS9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
