---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-favicons
  namespace: linkding
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi