apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: linkding
  namespace: linkding
spec:
  interval: 5m
  url: oci://ghcr.io/pascaliske/helm-charts/linkding
  ref:
    semver: 3.0.0 # {"$imagepolicy": "flux-system:linkding:tag"}
