apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Ygc7lIcRFQThE+IdJIPsr7aqDvsc6IfXqxKv1tWQUx6t27pRfw4Pv2HFcQY=,iv:TzQokWmjOGxmI1xMIyaKnSPDXA9cVZu0SdQczc7miHs=,tag:BPhEz+fhE3CwHOcl0pr9iQ==,type:str]
    username: ENC[AES256_GCM,data:0xO+rki2Skw=,iv:Iib0BssRunWJ1iDQZ1GVDi9wNtAUxWes4TsNO3pvBWg=,tag:JgdXZ9/9A989Ulag4QVfoA==,type:str]
kind: Secret
metadata:
    name: linkding-auth
    namespace: linkding
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMWdoMVA3Q1JZbXdFQkQv
            QXhINUcvYVZvcDBxbVZhaHdDVStXVSsyc2dZClpTTVBsVDR4b2NlN0NoM0hwcDE1
            NnlFYWN3QVRFNmo1anl4VkI1VnhaQ00KLS0tIGhkbFdadlpiZGJhenpxNWRnUzNU
            VlQ3TzJFbmIvR3c0M1BZYlVsckJETE0KglLoCYaBd55UPIFqF4fFBGb9ainVflW4
            Yi72loTXlqTwdyQvU6HYNjZZnhQzye0gzAw8TUCbUT+sRZ32PKrv/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T00:31:12Z"
    mac: ENC[AES256_GCM,data:KH6smwI928sJWIq+kVL+CI6/z9Wf8KVTjcAjIr6x9P6cOVgt9YYNqsq3HLOM/dlysjNIZQjQPqdotiJehQLOAjYXL9fIGUrkrQX4b1lFOzjOoanSYNGuadTHoLxI54aR3L9rqD04hIbPSprAGvDVgclHe7qtLvHfAl0DO97bnLE=,iv:gImDSSlGLKLWCP17UAU//snhT1HsA8yy+0GnWQfi1x4=,tag:BufBYfcQmKHYnz/SOfkDQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
