---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless
  namespace: paperless
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 16Gi