apiVersion: v1
data:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:iwZt9xFMVG3dIjiv+wTltOk3llriy404qdHm0V8CFQYX0+FBT9QTE0J8JLZgQHQknzMrqB5FlDfHE4CCBENv2ROduWrzYiOIkbpXewlRtwo=,iv:w9EspHia6MkEv3IxjDqclxGMZebPKXUFtC+ClpaKrKA=,tag:2xoeoU/HObHW5QrtyfTXug==,type:str]
kind: Secret
metadata:
    name: paperless-secret-key
    namespace: paperless
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVnUwYkM2dTRZeHBSay9L
            a1htQVQ3b0s5SzFUWldDWFgyTzFjKzVUK2xZCkc0VHBuaHJsOUVsNjdBNERqOUtG
            bFh6Vm1GU1FRaFh3UG1OVkdsa1hFSm8KLS0tIG0rR1ZHN2NFTHlaS0kxM2k1Mkd2
            RU5TamRwN1NsbFBENzlVTGQ2UDV0MDgK8NsrNigekpIA4fesccPa/YSWPdruKQc8
            1yrJFAr0LRrcZYZPJIJxv6FzGcPYeXxBcLeZt3zPxSwig12AcB+91w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T23:58:52Z"
    mac: ENC[AES256_GCM,data:2zkjciARfVFf6wz+ZadljC8DeNqyzxp6S36mDe9ygYI8kurnUkJBpmsTCgYMNJyu3y9n1SPMr4HEylRElNXXXVQiZqe05QhviTuvKJJig6htpDWxd8Mpk1ou6RwECjkQ3wMh4575zlOUCmC+TeY9inLZT5/vYJaf7VxlbMp4hTo=,iv:hHlRTKyuqyrztueQAaKWprDstUQ62lLMWs/J2MSb1j8=,tag:OhpOZwSEekj5PaJydLqh6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
