apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litellm
  namespace: litellm
spec:
  interval: 5m
  url: oci://ghcr.io/berriai/litellm-helm
  ref:
    semver: 1.82.0-stable # {"$imagepolicy": "flux-system:litellm:tag"}
