apiVersion: v1
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:9SNYh80DQ21R0sFcbCWLxgF0OtmXUPTgbGKyYujCKgadMRT8zJsO4P7cm90HDq/d1NjfxA1xD6V5X5x9H1WCZOl8D9FV/aCDAiXxPfuf3qwbaoqaqF+RvOGPOS/hdiD7omv3h0KcJgmNv0yYtD7O8xrUXNIPUYLdVgaGwqieV7vP8sJdxg8aq1Y6tJzrAmop,iv:rmqnudRYfTzeZSMyXiDoGNDFTthl9+wiY+opX8g+kQE=,tag:JXj3oHQKuf+PrtyHAl2IEQ==,type:str]
kind: Secret
metadata:
    name: anthropic-api-key
    namespace: litellm
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTWNTK0FScnlCMHRTci91
            NzdUVTA5bStjMVkrakc1bHlRd1pObXFYTG5jCkhQL3JsM2IyVWE2eUt4OEZGdkVB
            R09iS09yYmovSFZucmJwZk1UZE8vWHMKLS0tIHZvSmRFQ0JNcHVOdHA3SnRLQ1RE
            ckRXS1NSR0lSYzNKNDJ4M1hWcjhVOFkKZaBkTGValxLmqH6PwAcVQon+1iC+fddD
            37NYJ4FBqVxMu1wHloBwtkChwQ7IzjQijRq9YuT3QLL6w/ia3TwHFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T20:50:44Z"
    mac: ENC[AES256_GCM,data:hbTcFeZ+z2T0t6L0DHV48AHE1Wif54cL+GjQc4ScQqfVMrN+sh/d1YVfAzNhbcFOp/gMWy8v7gGYaXgPHf1oEqPxAXjszb1N/UBPh+dFekME0LB4lt8dZxFVlRsEYknyAswRRCV/oTQkuTXo0F+aFD0cy+OgeuawJoxU0qcqkq0=,iv:LAuHNN4AxLK1g59UW6MOw6BEYe8n8UVBQo88BLGBV2A=,tag:tLWoOHKNXi8oeztSUBPDVA==,type:str]
    version: 3.13.1
