apiVersion: v1
data:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:RPbdZpidxXxiwEusFaY76Uh9Tiy4Fylmr5I6VTHNYw4cOGiLUShBTQ==,iv:Fg9CJSlNeCv5TAcEwXwdt+JP4GNZpJbqUL+5jIOv56I=,tag:Zj2AV0cvvrdYzG3B1TA65A==,type:str]
kind: Secret
metadata:
    name: litellm-master-key
    namespace: litellm
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRUkxdDNlWHU0czRsa2J1
            a1BhVkZleDVyQ3FHQkxxRktYTk9RQXNlQUhnCmowSW9oTVQ2cTdHb1VBNTFjV21E
            anhOYzlFUE1SbnFsWXNWYTBIUy83N2sKLS0tIEEzRmd0MDdmcDVEbzlzRGRPc1ZQ
            VW1kNVM0SUp3bUNtU3Y0SFJPN2Ivb1kKU+Vyzzh2XKtBIj43fPsdAt8DiE2kipf1
            MxezrWct+trcZZNSgb78pwL+TcENHsmrCUwV7zx+D9Gpa74D6kLpUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T18:54:38Z"
    mac: ENC[AES256_GCM,data:cmFJMMfUwR6gd+1L46t336yiTCL1GlRvJ5kE1ceLAhwSqhARxJ9inILtFFW4aTv1ax1ZRhUwSknS+iziRmx63/ir3WiLYdj1398G69zG5HriXUuTDwPmCJsh6nPZGdZxW2e+Aahf6mPlwdGzM8IAKan8wKiT5cbyCecF6uLHH5E=,iv:i3MdSXMw5AjFrber8yWp6YAWpjVV1L1TcRuc5EtzIl4=,tag:ykR6aU/An8l2qRX5yqUwQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
