apiVersion: v1
data:
    XAI_API_KEY: ENC[AES256_GCM,data:fcqNLDgdBNSJBNLX3nEusI5go50gRtRzUwrk3Y5/KtfXRK2SahTpn50MxCLOttoJhxYqgJT/EkSVo4dIJZP7R6ZIfKj+emhygRvC91RuCqywcDoDuPgkyLFG+g4bkyxGJh/dINHJ0ziYXOctr0eyJg==,iv:bNn51WlNVyfEheWeuEPipZo1QUJSBIG8BRpPrQSo5RQ=,tag:XvZBHR954hfBU5P4oKBMzQ==,type:str]
kind: Secret
metadata:
    name: xai-api-key
    namespace: litellm
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTERZWTRoclRoT1plRjJM
            bkx6cFJXVUQ0U2oxRnNZQXI1U2I3TlYyQWdzCkJ0TFBMN3MyVVd1cHVSWDJhekxx
            YW5CWnBwSTZoS21hbVNKWUZ0b3UvYVEKLS0tIFRRVVJ4NmFGVm5WM2ZxdzliVlRI
            NHRuZzR6NUIxb0x2QnYvMmVRZUMvR2MKs5KrXrmvSMb2Bb9gRt1lBAaHYIU7tHQ/
            UL+t5ww++u6oNTomREj/4QW2RBLccG6HK80HRyE9x4AsBBafyu/i/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T23:41:17Z"
    mac: ENC[AES256_GCM,data:+8QsHbVt8poCxfVzBkKidUjQryuGSwzesXtcQpCX6ZMKCrj1pms4I2w7Ok3t1BmF5SXOrOBVMna2UxX68f07njKlNrhx1vTybey8NVLRKOPU5JcgmV4VHOhxZeHTRfhFuwUE39pfLCY56eyzWlZiKYcHGUYEdTLMESONCgFoKOE=,iv:7gFnsXnmLIgFt1D6ELHuj5FTO/bO4uqFwtlmr6/3T2Y=,tag:wAItgSqtACCRlR4jN3GoyQ==,type:str]
    version: 3.13.3
