apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: linkstack
  namespace: linkstack
spec:
  interval: 5m
  url: oci://ghcr.io/adnoctem/helm/linkstack
  ref:
    semver: 0.3.1 # {"$imagepolicy": "flux-system:linkstack:tag"}
