apiVersion: v1
data:
    password: ENC[AES256_GCM,data:8F0txtB1rXqNCV9QtGo8sJtv1qVJ72n4dikuUAhFjQL4Qd7q5lyzjlcvUZU=,iv:IAKbrDCEHKFn+7KnUlC+EVA7UBeDiOfQbM/jyuhgM8M=,tag:cbrBflLhSI3dt40inWEVNA==,type:str]
    username: ENC[AES256_GCM,data:4PztEYenb5vB/VJy20Pbvg==,iv:GrL24WyJ5j3OYOQrIr21llbLrWF3ZqGFkFytJVy+TQA=,tag:D8bPQhlpPVYq/X3CYEPVQQ==,type:str]
kind: Secret
metadata:
    name: cnpg-woodpecker-auth
    namespace: cnpg-system
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "woodpecker"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "woodpecker"
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmM0tLWVZyKytqR0ZpdEZM
            dlZNbktzQ1J4Y0JvWTBsNHpiWGk2WHNmdzJJCkwxNkVSYUl6T28wdmhzNTRDTnJy
            YjFjS2NkL1dqTGM2eUtUL3VhMGFIZ00KLS0tIHFVcG8vQjk5aHFRZnMxZk1uRGlE
            K3dPT0RlZi9DanVNQUY2N3VhZnRZeGsK12MXDQSa8W0rKjdl01AhR8V2jD9w7Zm/
            Y7VUJ4ZkMnurFfCXEGITj5UfTD5oU0TqiSfWfsU+w9pQaBv3sDN/4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T16:58:05Z"
    mac: ENC[AES256_GCM,data:FjSCBKcqVIzI5e6h4PE6I76352nqMIFaG/u4ByFd4lQGJ+QGjNxiwmV2rHa8s5ovR2pcC80cq/SDaEPnT9uognl7XNIrslJZRudbm8ok/jBauWnJNrgI4s2Fru35MM91NwKq/XnbBb2imOVQw+1D7/zXPHYDjRBywxdmKGrYN2Y=,iv:pGaDfzG6oiWzphp4B9ZYwOXa9lGx4xNoIZ5YsVYcmmY=,tag:10NAjgmreAkCM4yIzAwtxw==,type:str]
    version: 3.13.1
