apiVersion: v1
data:
    password: ENC[AES256_GCM,data:TG3H6eSVNELmV9vQ/5d3eqmgToCrRShbzSROzWoFc3Xqqu7gc+WMRuO9cik=,iv:z4TwiP9bUGEDhgnTrM210/vsyg2dqLDCWkZ3XbJTmrs=,tag:DkLHA21vJKaDTeUhYCzFqg==,type:str]
    username: ENC[AES256_GCM,data:/wJDYE1vFuMS3fEN,iv:ctMvgRELV7IADlyjJXkmS1nwGWsf6LyIi/vkqO9Pngs=,tag:wKC0SwmMLYitqflOG1zCEA==,type:str]
kind: Secret
metadata:
    name: cnpg-openwebui-auth
    namespace: cnpg-system
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGakpMNVlUNXZrQUJQNEhM
            Zm9IbTZPRHEzV0V6QmpCTlRYUHBEcDJnZ1JZCmZuamJnWUpTU09PZmpkdGVjcUNq
            QmR0MExmSzR2UnJzSHlVVElMcHh6M3cKLS0tIHZ3TkdlWSszdW93ejdrWnl2TzZG
            eXQ3YzZYWkZHM3c2cnA5YytyWjdOYVkKntkNVoydnOPZG6NqqwoT3jxrSZI9d1be
            KR/v61u8435zkZBt4xszfjnT3D/ufeSrHXjAF/q8Jjexe68CksHfzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T18:40:35Z"
    mac: ENC[AES256_GCM,data:GFTq1UDzbpE7+1P7QZlhNrOgEJZIg+GTwsuZX6pIiK9+y4SK5xhCniVMyhV1XmT3TQ7FYhZHT0QcYiAdWOtoA6TOnS4Iyd5rUEuipLJAERVuBdshDC826GxJR/3Q3MRcsVNhXcAum+tteUdcYJZt4HjRgY9XawD/H71s7jQWCMg=,iv:mFxoHTekHPI6BWUVxMWrH26LbrYElMuAo58Ytn7uiDc=,tag:2QNQi2CAJlDJgGGwYusiFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
