apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ZI3H2YMnPVLV9Zt+wFoGYFzIMxoXGA3MWDJLNOTTRN34KxDNimV08M8qsuk=,iv:CI6ADLdTmDngJ+3rAHJe0q0JSrE6mTqINz/LupzA7A4=,tag:sRn1hO65tzePN3P2jXznHA==,type:str]
    username: ENC[AES256_GCM,data:fQRi0zGAE3lpMcIH,iv:IG74dPOlnP6WYjdcK94CqPuJoTAnUcRzzb6lAbZcd8Q=,tag:0Gq9UYvbkdnwIEV+WEXyUw==,type:str]
kind: Secret
metadata:
    name: cnpg-outline-auth
    namespace: cnpg-system
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrR2pGQSsxZzJwclc5b28z
            eXBOVzJtcDAxVUJmMnR5cG5xTjQ3dVZVMm0wCnBIRTNaLy9sSkh3bzloS2pnbUhM
            V29Pc2FRbVNtN05tbTlYR1VtTjFNVjAKLS0tIGgzaDRSY0lKSHhQKzR1eUJTMlI0
            SWdheDFPbFVqM0hXSGg2T0FWU1FXUlkKsjTVs6xuLvJH+5Fvmynfsu9l8oFbtHC6
            YUcuq6+H8hsyvIyvmhuAZA0eKoWQtn82H9GN+6VsRaWv6O07At3i2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T00:26:32Z"
    mac: ENC[AES256_GCM,data:NC3/QQ5b7KgGtXtIL3dScFaMLAn5NsSyqTL35HhbogmRogHlzdGkDx0/albJNbmjb6GPnVOiAp55S2R6JHPgflBwTmx2bsQf+B2XCMg+YXC+BH6lV0+AojBzeBvZr+1K/zAotUz/GVHGa8CSC+pgszdU0Nvtg3s+JfyaPEGXQtQ=,iv:jqQxJKi5V6YSIuqIE5xE9CcovOceItUg3jWkEHxSQLE=,tag:PNznV9jH58qlt3TB4iSKsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
