apiVersion: v1
data:
    password: ENC[AES256_GCM,data:mlhezMxLDTTrezRj2NwGOlJC4IRGDpzSUJHZi1EGlibPG3o4QIEl5VmluvE=,iv:ixx3D7iLwmDDt9jJKeBtkex3NvYlMmJHgu58B1UZ+ps=,tag:9L408cfgK+p3l78rBNpszw==,type:str]
    username: ENC[AES256_GCM,data:AR+B0g2dWsSNnfYc,iv:vuJRBLCOOWRmmp4C657afEpGbv+yh3if2SEPRUSLxXs=,tag:c2rxkGV9l/9pWxOqP+Kbhg==,type:str]
kind: Secret
metadata:
    name: cnpg-litellm-auth
    namespace: litellm
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXd3ExZUxNZnMrQ1BRNHBF
            ZFVHTEZDMStSYTZFd1V5T1RkWFVlMFUyOGxZCmlkcnYvY0NqNkowQ3Y2S0xCam5N
            SFdWM0FLSUJqU0JqKzd0alhHVVo3MWsKLS0tIE5VQjg3SnFOQ29yT2EvOGs4M25D
            SWZEdzRLRm0xTU8zQ2NuRnc3cTR4YW8KpjfOq7GuTmkFPpw9FTXMWslKVylumyxx
            caprbbUu8dmlctKV+GFWXvSpAoeZxWcNiB0WXRNp5V8EZcjihF5GPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T18:37:39Z"
    mac: ENC[AES256_GCM,data:DFBKAzYef2Q4vWIfhHg63m8UtJaPuLoD75/FQF0rMYMwCHS9OSZOkBwLD64BB7uCsanrh8zm+wxh+iBVkTQD4FlJnREWg+bcT/+uLr6bzIqZdxqVhCYIVnjc/GGFOZ53NC+/xSKXF1rhnR88BAzXv7M/MXYdu0A7cT/i684aTNo=,iv:0sIwgxrLrK3UFzbhc3qUU8Mwb+Mm/VasxDdydtIZ7rQ=,tag:oqlMwweMlkBSq9xWtw3UhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
