apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: redis-operator
  namespace: redis-system
spec:
  interval: 5m
  url: oci://ghcr.io/ot-container-kit/charts/redis-operator
  ref:
    semver: 0.24.0 # {"$imagepolicy": "flux-system:redis-operator:tag"}
