---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  url: oci://ghcr.io/traefik/helm/traefik
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: 39.0.5 # {"$imagepolicy": "flux-system:traefik:tag"}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  url: https://helm.traefik.io/traefik