apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: outline
  namespace: outline
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: outline
      version: '>=0.7.3 <1.0.0'
      sourceRef:
        kind: HelmRepository
        name: outline
        namespace: outline
      interval: 5m
  values:
    # High availability
    replicaCount: 2
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - outline
            topologyKey: kubernetes.io/hostname
    # Misc. Configuration
    extraEnvVars:
      TZ: "America/New_York"
      CUSTOM_FEATURE_FLAG: "enabled"
    url: "https://wiki.cvsickle.com"
    autoUpdate:
      enabled: true
      telemetry: false
    image:
      repository: outlinewiki/outline
      tag: 1.7.1 # {"$imagepolicy": "flux-system:outline:tag"}
      pullPolicy: IfNotPresent
    # Database
    postgresql:
      enabled: false
    externalPostgresql:
      host: cnpg-cluster-rw.cnpg-system.svc.cluster.local
      port: 5432
      database: outline
      username: outline
      existingSecret: cnpg-outline-auth
      passwordSecretKey: password
    # Cache
    redis:
      enabled: true
      auth:
        enabled: false
      master:
        persistence:
          enabled: false
    # File Storage
    fileStorage:
      local:
        persistence:
          enabled: true
          existingClaim: outline-file-storage
    # Authentication
    auth:
      # Google - https://console.cloud.google.com/auth/clients
      oidc:
        enabled: true
        clientId: 1069333890534-e8aj314ukj0olkvvcm6n1l4ovl1g4gk3.apps.googleusercontent.com
        authUri: https://accounts.google.com/o/oauth2/v2/auth
        tokenUri: https://oauth2.googleapis.com/token
        userInfoUri: https://openidconnect.googleapis.com/v1/userinfo
        existingSecret:
          name: outline-google-key
          clientSecretKey: client-secret
      github:
        enabled: true
        clientId: "Iv23lixsxFHX10XBv2Yo"
        appName: "outline-cvsickle"
        appId: "2637597"
        existingSecret:
          name: outline-github-key
          clientSecretKey: client-secret
          appPrivateKeyKey: app-private-key
    # Resource Limits
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        memory: "1Gi"
