apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus
  namespace: kube-prometheus
spec:
  interval: 5m
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  ref:
    semver: 81.5.0 # {"$imagepolicy": "flux-system:kube-prometheus:tag"}