apiVersion: v1
data:
    password: ENC[AES256_GCM,data:lE+PiDLnRgbWgaR9h0wtcYPeTzKh2mnwF0QimPazxvEYFzyIUjJQhNrN6iA=,iv:aNrJQnKCfNQu9F2XML0uEvvC0gpAlLNICB6QSkgCnhc=,tag:IOxPdBGGkGwDl252UASXPw==,type:str]
    username: ENC[AES256_GCM,data:fQyNrRRvh3k=,iv:XeC4vd5STyVuou5TW/zbIM5Fs1kcy9WAx3psdNVdT1I=,tag:My0AOy5e5r/tVoVRdSyYTQ==,type:str]
kind: Secret
metadata:
    name: monitor-grafana-auth
    namespace: kube-prometheus
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aTNhY1V6eGVtL1Jqaldw
            Y21Tc254OHU3VnZORXdsTVlXNnBKSjI2blU0CmRNRmJCWHgxeHQ4WkRhbmNmY2oz
            ZjIvQTVvN29uYURaaTlHMllQT28xVm8KLS0tIE5PL1VZT3BRd0tQMWdmMHk0ZTFn
            YStvSHZtRHdpQUJVWDZmNVhHZnFrMVUK2tNQFGr7ogQqcoIaSC5eWxKyZ4wMvPdk
            pqDh3+TC4zRT5N46e9MjAduQO5Hg4PGvOBkmpxCmR+q6dkCk71Sqiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T00:40:27Z"
    mac: ENC[AES256_GCM,data:5JbnLjEhuROV/19G68E/nnjMzDqsInPffy7WWcszAs9ZGgJKbcu/dKhXO95INnW4YNK23MVxCIkMAYGa8lzOeCjQbVaP03Z4oJDcKG6/XFj1qX+ifiMzsYOs62fSYVi+vsoho6FVbWeVPkv53jbhg0+RmqSZcDoUJ5jJ3U7DzKM=,iv:LfxpxAD6lj2kZcwReCXoOguxjhg4ws/Y+FnK18gBMas=,tag:tyHQyQJmjKAYBIzzwMAI/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
