---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: longhorn
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: longhorn
  policy:
    semver:
      range: '>=1.10.0 <2.0.0'