apiVersion: v1
data:
    CIFS_PASSWORD: ENC[AES256_GCM,data:eO7+9qo42mUcxC109IrMpmIBGYg1FEnoJTgRCBGp2xOG7vQz22y3xqpzVEw=,iv:iSSOZYfSPge61gbJZWkWAQb2KVhx02hEFulrWIv8D3I=,tag:7/mUO9bshBqgP7ppBpTxFQ==,type:str]
    CIFS_USERNAME: ENC[AES256_GCM,data:kLqHaHkvCLN17x3d,iv:tKzgE4Xk0rMOyCPkldHulhrGBzIyR8kSzc6go/7TkA4=,tag:IxlHQV1hn9S+NIE0o7bKew==,type:str]
kind: Secret
metadata:
    name: longhorn-cifs-monolith
    namespace: longhorn-system
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMTRLcUg5VDA5VGIvbGpq
            WTQwRnFXdHoxNjBpWDJBYnhyT0dQMkRkYW5nCitEU3ZZK3RGdEZrbGl0QitHTE1D
            dDBXRzFhakh5ZnhFQ3NPajJ1ZWMwdWsKLS0tIGdXUHNxaWRYNHBRenFtT21aR2k0
            Y0t0d2hvLzJUL2xjZzExUTRxRXJ5N1UK1DY6uAfcKzEGGdxHSaz7MFn8DvST68KJ
            TKcbKIAbBheuULvxxqSpWNdEGXA8pLUIYR44phrPLLD/7vgFbBENFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T19:43:15Z"
    mac: ENC[AES256_GCM,data:o6CR5hriheVHUBb1JL8vodmKIKF3N8B9XPJIrsEde3UHzYx5ocbM+nO/Z7bhXcKP+HC8BZ9PzKUnNHu1zJIqgleRhLZS9xRmS7LffB8cuhVy86CVIq1afyLfK2MvXvEBSFbo1pDo2wnKSNss6PsAg7ajgDAlX3ZJBzYYP66e/Bs=,iv:fDd7MC9Dz/X45uHQJZn6WfkcmHcgDVRxhwF8kLMM24c=,tag:p98rbJADUvhFJLevG0M3Bw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
