---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: forgejo
  namespace: flux-system
spec:
  image: ://git.cvsickle.com
  interval: 5m
  secretRef:
    name: forgejo-registry