apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:+Z3qOfeuCrjq+eAZRyVKWtDz/m58ASpl/CHcr9QgL6G5UQb/J09csTzqhWOqTtJuSVSyMj1sk9m80WWN3efMFzyBh/ZK30PVn0ajGUMGtXTLjP+0ThTZPRy5jRihNajk6kwTL0ly6RgSRzadggm0AE/6eH9xXxqHXGA/Z6WGl4AdF8TRu1XybHoj3YFynyxZjntAui6uXzVFoEyo8eg+IngwK4HE7O8lzCukQjqndsavF3rjUyZSWZJN7biGbHOzW9UPQvsWxec4A+PD6ziDqCxhZ0LDefxCekJQBpQtCxUZn0SdYIuFYoN0EHjlh1quqG8PYyGtuYA3LFV6qu+4PL2C60wvbSRU4Gm/Y8dXGrlmNIE1eEDjPskRQK7w69GWIjQEh9ItmUs=,iv:pc1tdsxpx4j/MJmSR3cro9LmF/K47P8SXpLtFZhzGOE=,tag:A6zwaqBTooxz3FTH+m05dA==,type:str]
kind: Secret
metadata:
    name: forgejo-registry
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeGl0aTlvWFVmTytMd3lQ
            ZmNuTzZiUVNOdFg4bXFicndLYnFXTSt3YUVFCkVHVk9TUFpwL1kweGZUOUNzRXZm
            T2FWY1grYW9ESUFRZHBabFc1Y0JjSVUKLS0tIHh6ckQ5b0FZdkQ3RFNRbU1aTGl6
            ak1QZjdreEJvc2tsUEZ5dW1QQ1B6R00KIlm3xVyDB+ydJRu9wnM5h9WF+n80AhjX
            Qhi60gUJC6jK8XW7t/azQTe/8Cztvs966zMdu7UEh75QJqAFUkMRDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T02:01:43Z"
    mac: ENC[AES256_GCM,data:qjNpaWmXJ1sVANz0SchCdXJbMZDGR/D8Zbxy6/0Bugu5SLyRnJAaD0AYnuqCrBdeqHBSN43efNP2/jP9Cae6cIIiW7V4AW5k+UJOCcevN2ILHco0uqzZtbaBPsgQTeMoYV6Xw/fuQ9lSBUsNctu3so1HtqwLCkZMdGLQkWEgc7U=,iv:CGV0h6Zwq+NUeECuKp7frNK+rVo9LgxJ1849qfu8LkI=,tag:Q4UXWQ5BaqgYM3+H6n22KQ==,type:str]
    version: 3.13.1
