apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:+qMi5nrGzyF4zXjTd/d+giXhjYi+fWe4EeRaQODJi6B/f7XrOjzglAppn5comc+O0jXsS5ePMIYXuORBjVSQE0dk+PIpdO+blL1BGb+dMBRNLz84+RnMf4j8zen/3Fzh5YAMlGJDV1g7Obs5eQ6PpdIRk2l0gcFuiaUvehh60lerFt6U76qgRdsRnm2mKFKs5M25yhp5PbqT8QPZ73aJaDFamjPaNGXARCkO8WeTMJopY6j342rtZ3UB8SgtEpeLyHKn6PgI44q7A1znnySnm9m0B7dMMdH74geOdinxa+4tEZZLAwX7L+6DfrzyClY/Huw8Qe/brR0SLbQ66v00CljJN6kZ8HeVJYNXOEqDq1jWML2Je11FSVpHmKwvVgRBEE7l2isQPjY=,iv:zgJpyE6EV8BeCvGJpITQFkUsM2O2lmaBLnMzw1pA3Ck=,tag:VCSIZaXzsBJDdgnPnIB4Vg==,type:str]
kind: Secret
metadata:
    name: forgejo-registry
    namespace: flux-system
    annotations:
      reflector.v1.reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "cvsickle-profile"
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcktyb001WEpONks5SEY0
            SEt2dWU5SzdvZWtHMHk3ZEdpZ1ZFb3Exa0U0CklxazY0a2lnUDFBWlpuTzBiY2p0
            cWk2cVNLN1dzdzVuVk1lSnJaSzY5alEKLS0tIFpZbDBHbEFVeFhRVGVZamk1MEZE
            aUY4bk5aRFNiaGZDTlpkcU9JWHJORzQK+iKAdhL/5kd2s5uGW/eQtkgTYBCJ0uWe
            WaACaYR36CO4Hd/2a7eKBRJkvE09L2eSLq9Hq351gfgzbUVv7913YQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T02:08:11Z"
    mac: ENC[AES256_GCM,data:45bSUNh3dmrhYtlq1AMWKxNpWR09BDLNiVB0yvszbroicmnvxFLgCy1DDwm+y4hnv+wuTCyauko97L7CieP3+fSesosBcQw7JvId3/CbBjHvI/XzyT4K4L2uq0iEVb+qJn+vwVhVQ/Nn2x5BLZb1qpr07lIXOwSLLfv72wtEAAc=,iv:T0D3K35gC8aDQ5sIvEaqKB5PxrbgsK6YOMYijXlioE0=,tag:EsMlIjXg89Pa/isFRohXoA==,type:str]
    version: 3.13.1
