apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:9Gnk50xOS1qy/72yDprXfjdQGEZkRLzr1TE8z2yrRXbHntDoCyXNYmpol9HQQQrjee3Pq/PZIU5NHmg0h9Y1YlB9tswXYGEmrXrYoCa1oHyJ8gUtUZhbX1DMWC2n7Q6aVCQOMU0dRUdKJkFcojUdU3/9TmIoybNeapcForIlIMQjRmzEjgJkFEMTSVWrRyRVe2sDiW/N5to7RO1jaEdH7mSvhhpdQPHEt1hejxKGZRWfGWaxoVxESOOMuriFG+B/XRM8oJtLWZWX9chcPxEMV/4QmvkuB3ml3IjRaDsZdyTyv9LyDQULCvqpQVVn4dFD6kd2xUbbtAmOE7do,iv:9ICJf3NHsTom8/vSExsxMhC0KeWNvUrlWFRUicWSaTg=,tag:Ch+an0S+1mJ/US3FRkjIAQ==,type:str]
kind: Secret
metadata:
    name: forgejo-registry
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN0FPR0wyeTRIY01BMlpm
            VDdrV25DK21XbUNGL1lkdkNGZDg3STZXTzIwCjMrR0VNWjFNV3FxUlZsYkZKdUpZ
            L082OXlmY0ZYNUoyQU9XbXNrTHYyODgKLS0tIDdMWmhtdHR3THNwWk1OamNCZWl5
            QTExS0h6NU1QVTByQU5Ld0lwVXorQTAKvpasJ1LWvdHuM74fmWGVxDfnKQNCsqiJ
            3/3X1/MvVdYqW1z70CHN+yixPRHPLUEAS19vcIcnpgyWx6HqBTqwSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T01:48:18Z"
    mac: ENC[AES256_GCM,data:d02W04oojdqdld3cPMavPDrELpadD0TP1Yh7H2otM/lKRri1c36PkoIRwZk8yGE06jNL9xB/+xqCmas9avoOcxSqm9jvOhrW+BFtnWU7ZlWxARHHEUyCil5Wf65hqGgGM46i1MkRoZhC6+VsKip2QPJjVJfK0jMQfsggTIzul1E=,iv:UOxnzgaIegikzVOo6eR2FiTDQd3VosYM2iy/Ubn7m/U=,tag:/fGPCd0fCXePYIKGgJbipQ==,type:str]
    version: 3.13.1
