---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  image: ghcr.io/prometheus-community/charts/kube-prometheus-stack
  interval: 1h