---
apiVersion: v1
kind: Service
metadata:
  name: paperless-ai
  namespace: external-apps
spec:
  type: ExternalName
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  externalName: 10.69.1.52