---
apiVersion: v1
kind: ConfigMap
metadata:
  name: littlelink
  namespace: littlelink
data:
  META_TITLE: "CVSickle"
  META_DESCRIPTION: "Software Engineer | Gamer | Twitch Streamer | Content Creator on YouTube | Homelab | 🇺🇸 🇯🇵  | Full Nerd"
  META_AUTHOR: "Corey Van Sickle"
  META_KEYWORDS: "HomeLab, HTML, CSS, Engineering"
  LANG: "en"
  META_INDEX_STATUS: "all"
  OG_SITE_NAME: "CVSickle"
  OG_TITLE: "CVSickle"
  OG_DESCRIPTION: "Corey's Hub"
  OG_URL: "https://cvsickle.com"
  OG_IMAGE: "https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg"
  OG_IMAGE_WIDTH: "400"
  OG_IMAGE_HEIGHT: "400"
  GA_TRACKING_ID: "G-XXXXXXXXXX"
  THEME: "Dark"
  FAVICON_URL: "https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg"
  AVATAR_URL: "https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg"
  AVATAR_2X_URL: "https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg"
  AVATAR_ALT: "Corey's Profile Pic"
  NAME: "Corey Van Sickle"
  BIO: "Engineer | Homelabber | Wannabe Developer | DevOps Enthusiast | Full Nerd"
  BUTTON_ORDER: "YOUTUBE,GITHUB,GEAR,DOCUMENTATION"
  CUSTOM_BUTTON_TEXT: "Documentation,Recommended Gear"
  CUSTOM_BUTTON_URL: "https://l.technotim.com/docs,https://l.technotim.com/gear"
  CUSTOM_BUTTON_COLOR: "#000000,#000000"
  CUSTOM_BUTTON_TEXT_COLOR: "#ffffff,#ffffff"
  CUSTOM_BUTTON_ALT_TEXT: "Tech documentation site for my videos and more,Recommended Gear"
  CUSTOM_BUTTON_NAME: "DOCUMENTATION,GEAR"
  CUSTOM_BUTTON_ICON: "fas file-lines,fas gear"
  GITHUB: "https://github.com/cvsickle"
  #TWITTER: "https://l.technotim.com/twitter"
  #INSTAGRAM: "https://l.technotim.com/instagram"
  #LINKED_IN: "https://l.technotim.com/linkedin"
  #YOUTUBE: "https://l.technotim.com/subscribe"
  #TWITCH: "https://l.technotim.com/twitch"
  #DISCORD: "https://l.technotim.com/discord"
  #TIKTOK: "https://l.technotim.com/tiktok"
  #FACEBOOK: "https://l.technotim.com/facebook"
  #PATREON: "https://l.technotim.com/patreon"
  FOOTER: "Corey Van Sickle © 2026"