apiVersion: v1
data:
    password: ENC[AES256_GCM,data:nPBdRGQj/SGi+v4DIqYtjmP+/+o3eMPLiZH6v0nK9uYFz3hB1dZ4HF2wqNU=,iv:W7BU5uLEQQDON6SSLbPzw+PBtjQzulANsHEmGiqSjnY=,tag:m1BBIQ1KI4pnN+RPHhoPPg==,type:str]
    username: ENC[AES256_GCM,data:shzfXrQZxIPkIM6G,iv:vQrjKt7zTrqpfQPG07es4oYq7mX7VTvGTJRosE/4r/Q=,tag:kxEBh7bB8zvqo9iNLWQiWw==,type:str]
kind: Secret
metadata:
    name: cnpg-paperless-auth
    namespace: paperless
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUzd6b1RQMWMwblg3Z2t0
            VjJzbnRuc3hwci82SE9VM2t0dWZJYW1tMmhNCnJjZWVRNXdkT0FpY3BwcjVJMFFM
            QURTOEVoWXUvUzlEeWlockN4WDcyYlUKLS0tIEZYR2twaGh4eVlUMGN1aDRMZ0pt
            NlA4QlY2QUpuWU9DNTVpbkduMnhkNzQKlEZcdQYj25iiHmVGTobUG/PyAB5xBbz2
            MULDmr6RY9hbF+jBO+8OKpLTmQkssYhZUS76sRVXkMKNMTDJiY0YrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T01:01:38Z"
    mac: ENC[AES256_GCM,data:RxR6u+QVykYJayJo55UPTPVzWHX/W1Cw5wkMnzlfojxgG50cDubsKmqdPULrqkmcdtNPk0AodLSQeoXTMB09B0u04MfhXpsepaW9D5YpPNyzIGzE8Kkz7DqmhOKBOFqRGwmV+9Qb+TemSlIi3ffIQAMKd+vj7XQQDLPN0e/XK68=,iv:qmfid6f4GvJ+eFhk0UVFsG/QfREg7sX/VoamNqjYfOM=,tag:KtNhchVb5YZGqgjnN4Y58w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
