apiVersion: v1
data:
    token: ENC[AES256_GCM,data:2NVwk4KA+gi+HtWzfV5Umnxm7jddropCz5si/rIW2piNlDodnz0itbU7O+6nXW8g629wqSlURqqs7ZYS68GGpg==,iv:Qh9QE65Dv0Ee5wM15x6/bEW0p13P9xgvPPh9RRay+is=,tag:qm3GQS3+GkJluJUmJmFNDQ==,type:str]
kind: Secret
metadata:
    name: telegram-token
    namespace: flux-system
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSb1U4NTR2NDBTcnh4OUg1
            UlR5MnNHbitOSE9SbHYzYmV5MTFjOEhlS0N3CjJFTmFySjU1TExPai9QakRmbS9W
            NHdTcUd1RGpDRWd1RmRhR1ZUYzNxM2MKLS0tIEtDVW9YSjhwTER2TjZaUVplRXp0
            RzMyK2hYeFh6Lzk4NFpOeW5qdEZqbU0KDQZq5EwI2RUbnqsvKTBUa8atO7Ikfr+b
            Al80PYDFrBVXEpl/J82jCO78TyHKv71J022Lghjub+jKeBmA8oNPWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T00:18:27Z"
    mac: ENC[AES256_GCM,data:rYq7VipY8qqun7HKN5vgdBjpVNMPNI7iXMmeBrrEFcU5ET3DcQdMJzJi2gdt2S1oCQErdG0GUZi0URkIoBVgj4pixJVdZbfy4xO2WsTuZZ92VrNXfYgynlnMGVrfkAT+tq/25a8guaC1mWmMJ3R5B/ophBwfH1NFpXcDfh/vdS4=,iv:rX09QBZlkjit64d6fyZHMBnhjuMNuHiRIpNr+7OSdrk=,tag:d21iYLFG5asw4AMdtdFRBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
