when:
  - event: push
    branch: main

steps:
  check-environment:
    image: busybox
    commands:
      - echo "Woodpecker CI is working!"
      - echo "Current user is $(whoami)"
      - echo "This is just a test"
      - uname -a
      - pwd