apiVersion: v1
data:
    password: ENC[AES256_GCM,data:99pD4feCb8VaPZZp601ntCuddzgwXdDhL+HDCHKi4G1bdZZAEL7e6sZmSuU=,iv:gcsJPgGIqF2fHNRMnD+RHlBTgIt35VR9B0g+dIadEFg=,tag:+7OjNJjoP4T3EiVgL3nGVw==,type:str]
    username: ENC[AES256_GCM,data:/Re+K2dNkW3agyoAj4M7sQ==,iv:ueQ9kLP1e3zZnAEIjj4lKJ1dT0JIV8ZnW4urAx3/0uQ=,tag:Yg/kgsigrNapB2misfT+dQ==,type:str]
kind: Secret
metadata:
    name: mariadb-uptimekuma-auth
    namespace: mariadb-system
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RWlyMDlqeDk4RjAyWm1l
            ZmNEcis5TW12ZlNmRFI4OFlSKzFEK1plTXpjCm1zSHA3MnI4MFVTQVpvc2l5VFRa
            a2wyTkczSTA5YUV6R2w4VHo2bGxpb3cKLS0tIDlxK203VWZGZXF0QVN3b2pSZDJT
            bEhCUnEraS84OUt4NnVWbTYrRTJHQ3cKnf6QPRjtxtNFwkiRX5kalaLqOsApz8qx
            4LTLF3Ktuy24wVEptnoHlpN7RO7uu1vzVZkN+TOBCTprKqgaarUelw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T17:46:40Z"
    mac: ENC[AES256_GCM,data:DaRejolS2YBKD32qKes08/1pROlkJIHjAe2vxFW27mV4zFzlWWRPQXbDT+9+AbsiAZ1SFX4PyDtUAeUkCDAE9Nnw+FWAGF/0vTkE9zYtDu08lSbX/0tlPOceqg/NpdENv8CuwDxCG3K3BmIEASIN65EHRrYAeXPf4Fe2yj5TSws=,iv:KJP//bDt5gXzXm6DEXJTKCrWoLByHCkCGjkDV7aCWPI=,tag:xix64k8gGNhih7SQ+iXZbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
