apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:jEDQstPMFY1eGzhBYb9fkU8USJwTwWLJ9x1VIptCacwdoaazRlQuHdXYdLwyXKh6QQdPXlsuApyi88h4iOl/4LWsOwVWKvbKSGZJjPZjkiMcWRAjb/pl+qKZGgB5g9gOmyNXcw==,iv:8j4UKf2jA5AaZJeKHtP6bF98MOBc1AXGG/Dso67IMic=,tag:QYQJAEbS+PcA3E5MAc0lBw==,type:str]
    client-secret: ENC[AES256_GCM,data:AA/hWVUAgIRvU+GauIpBq8VymvQM2Sjg3H5R6DrDh22GCJqYv9+DosJJEnSLcuTe,iv:LA+aXYLS2jdDSmEk+8778mewWJlnJTLI14fza8Ayg0c=,tag:c9BAhSadEi3n60JvRLft+A==,type:str]
kind: Secret
metadata:
    name: outline-google-key
    namespace: outline
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVUhISno1OWJ5U04zUDVO
            emVEYllKMjJTK2pLZUJ0Mit4aWNaY0E1cFZFCjR4ekgzK0V4cnFURVZQU2hKc1Z3
            RXhEYXUvRm0ydjltYVl2M0g0MFE5cTAKLS0tIERYa3FqRDF4WTl0SEF5VlZvdjYv
            UU1ZZDVPMkdhSmxLd3ZkUXNIN0NmNDAKP2q6u6NGTGuEJcR/7myO8im4CN4cac5b
            +gwnyA0xdEJ05P2qMTIYobFyoO2XgKPKTo6AqV/8R0NJPTaTRypGRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T22:34:09Z"
    mac: ENC[AES256_GCM,data:dEWI4sdUrYqrQQz9TCLIKh+vX+AvL8fCNTxQusGLPWhjgQW3/1oSZ06vKpoXygnO7sdzQcmvSUeljNaU/hukM4zt8ZoSjrRzsEjgzhWfG92Y2dDMk0Yhu5yWei/U4RVpbuuiiiwxUszkLkR9waYkeF0e7tQqFL1bMj4GAq/rFAA=,iv:IQ+GoE/y7lSjcT05N9DCpMq1bnmv/zeGFc4/WCjF7JM=,tag:huqOa5j9OGWVqfsXBHo08g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
