apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cnpg-operator
  namespace: cnpg-system
spec:
  interval: 5m
  url: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
  ref:
    semver: 0.27.0 # {"$imagepolicy": "flux-system:cnpg-operator:tag"}