---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql
spec:
  images:
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.11-system-trixie
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.7-system-trixie
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.1-system-trixie