apiVersion: v1
data:
    password: ENC[AES256_GCM,data:4fg8AavzC31TophljzQiZ8mSY2nZ8ZDwWBcg+7no0VoI1M9+yZj8x/dr4Vc=,iv:5VJpskknk9KJyA4YrMIYhtCq/A51kFFIb712BLTTebE=,tag:L8w7rNCAUeyLvObX2jC3Gg==,type:str]
    username: ENC[AES256_GCM,data:DGOW5RmqZWtGFv1x,iv:0uEw+CnOz+7k1DEegxT4Eh/Mdjca927q3KIPZJApLbM=,tag:BsOAkNwsjtaejSEoqAblcw==,type:str]
kind: Secret
metadata:
    name: cnpg-cluster-auth
    namespace: cnpg-system
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVElrVHRRcXBERGEwdHYr
            dWFjMFRWdE5zTnFIODl1MDRsVkNreGh3ZXo0CmpWSzNsOVBUVm1iUkJvbnhVaUJO
            eWU4RlB2Q2JDcDJQbjE4SGxxM25lZDAKLS0tIGNGYlNKSStvc2V2a2hDYjdmUlFU
            WVBPRFc5ZFBmemp2eVJVUUtJVURkcHcKHP3nJ37FSJ60yRuFFpcJjzm4p9rI8EF1
            vBHswb83dYLB6ElasgSKi39zrdM4AVC1PRuPq+coAUw9KNPX3AkGmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T01:04:18Z"
    mac: ENC[AES256_GCM,data:DDwNTIOTc0zvOuAsmOzjd3eS2/LvDEK/QwmCfW6cfY4l3I/ypd3jEqNW2FDz+Hj6qPhScbwWQQqsDoSEDI45LJiYBh8+L/pgESv5MxPCmEjOf0pjl/maWj0Lstdh+ruZdDchnCMHRTmCbQRc94K+IPpuKDQLM9C2oAk+YBPG5kk=,iv:MbRCpMe36tlXs1PKpXf9W3hZUygez4zEGP0ewZI8ZjM=,tag:87pGYwBpTnm/deOM6RedFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
