apiVersion: v1
kind: Secret
metadata:
    name: cnpg-cluster-auth
    namespace: cnpg-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:HIiXS1k5y+A=,iv:6ao6NN/IqK0AvTJ7JBoH+JWLVGyjQPWDFBUZVAGEI44=,tag:/TD4hMKwdWMERG5KXReijg==,type:str]
    password: ENC[AES256_GCM,data:Uh1s1h051klpkEUs9VQiiIRY15CWaqVvm23iz31duGM=,iv:geOj2uFrrawnCFz9u9D2B7NDtY32zBWq79ZKU/zbpyY=,tag:4ITJpxFtFMZMBZt0LBIYaA==,type:str]
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYUc3dFAxcDZpQ1pYbU9G
            dDFsWlhwUlc1elhYTEpCUjNrbWV5eUx5WFNVCnM0MXRBZld1eDRjVkg0a2RCK1RS
            VFIxSVpRK0ZQbzNUUnhGRndmRU1TT0EKLS0tIHEvRmZLMmxKREJ2Y1Ayclh4K0hH
            NitMR3ZweTVDRTg5NTAwZTdVQ3pxZ3MKYGP/1jsxW5XUevGeG0K5qqG8UA1EumkI
            xAqGHmCIr27DpDUTTwSBMF/ZCMQ3keNzERmhts6Xc5s1CHW1FXG+yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T01:11:26Z"
    mac: ENC[AES256_GCM,data:sbu2uozoKVfefJdLbRekBAHq64dd2Z8kpjeaFIKPRkGY/JT6Lhj76t32J4lUQmNRkVw5zGiJ2SWgSUbemxvRjItuxuNHcindzEi6yKsMrPqcZQ5Iedyvr5SW+zMGb6xwP8wY4wVtLCJA2exp797sV4lDVbmTurQB0bh7tz/YHuY=,iv:URVdgXhPC2vAd9yFiTs/hFP1cgBdkP4UGVIguzmg+A0=,tag:1+qdkolxZ0WSIVhtFy9guw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
