apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Lw16VKtfrqQ9TE6jDyqIdbBS9VoYJtu9gWDSx74PfKyIyBqBPhISERqGAH8=,iv:54mnvNFwzOzvobUI7d12uxCB4BqqgvhY3woLru1kZ9w=,tag:SD9i4imu6MIBj8pUphJX8A==,type:str]
    username: ENC[AES256_GCM,data:A2v0HNBoE+k=,iv:UzqwiJVr/Ha+kY+xbxIM8d+6LTS1GKDcwrs91hJ+Vsk=,tag:RUE6nwKOTW/hElAfBu8dcg==,type:str]
kind: Secret
metadata:
    name: cnpg-cluster-auth
    namespace: cnpg-system
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVUJZQ1pZV3Q0OHU2L09a
            ODhoMThxMm5adDY3WmloSWdNaUxld2JUb1cwCkFUNHpNbzB5V2t4Z1JCaTR2RmVH
            YXc3bEw1K3Z5cS9xMzEyaEg3ZlVtWTAKLS0tIElZZkxwM3VMWlJINnA4SzFQODl0
            OE5wTVBZT2U3b3RLNWo2V1JGUWcvb0UKLgtIM+hjXYM6pgbTdjXxv5E/m6Z0Ziya
            OoGjeL1Wdge75PVZu0+w4SCDXorAvOleowB1DFURSt4vR7YLu+bVhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T01:14:24Z"
    mac: ENC[AES256_GCM,data:LYNmX0OH9puhMkUM4hnMYfrG/PiJK1DlN6hNQoxi4kzlKzxAGq429+1l/RM9dAYaFAGV0TQF8nTnbo053G9QWD1Nt3eFBe3EOxs+gcOdat7GW1tt483Y7difHDkDxeXjdOIU2Jfjs7BsRyh3yzDu+5TEbOfTETFTMF+XJL+tXKo=,iv:dHx3HP+8XCofoZgWp3RUVyWHCQUHEzaEhVNPBy8aLfc=,tag:1TAj9sSks9U1CMQRGH20zQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
