---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: open-webui
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: open-webui
  policy:
    semver:
      range: '>=12.0.0'
