---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 5m
  timeout: 20m
  chartRef:
    kind: OCIRepository
    name: open-webui
    namespace: open-webui
  values:
    # High Availability
    replicaCount: 2
    strategy:
      type: Recreate
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - open-webui
            topologyKey: kubernetes.io/hostname
    websocket:
      enabled: true
      manager: redis
      redis:
        enabled: true
    persistence:
      enabled: false
    # Other pods
    ollama:
      enabled: false
    pipelines:
      enabled: false
    tika:
      enabled: false
    # Environment
    extraEnvVars:
      - name: WEBUI_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: open-webui-secrets
            key: secret-key
      - name: DATABASE_TYPE
        value: postgresql
      - name: DATABASE_HOST
        value: cnpg-cluster-rw.cnpg-system.svc.cluster.local
      - name: DATABASE_PORT
        value: "5432"
      - name: DATABASE_NAME
        value: openwebui
      - name: DATABASE_USER
        valueFrom:
          secretKeyRef:
            name: cnpg-openwebui-auth
            key: username
      - name: DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: cnpg-openwebui-auth
            key: password
      - name: VECTOR_DB
        value: pgvector
      - name: PGVECTOR_DB_URL
        valueFrom:
          secretKeyRef:
            name: open-webui-secrets
            key: vector-db-url
      - name: PGVECTOR_CREATE_EXTENSION
        value: "false"
      - name: ENABLE_FORWARD_USER_INFO_HEADERS
        value: "True"
    # Resource Limits
    resources:
      requests:
        cpu: "100m"
        memory: "1Gi"
      limits:
        memory: "2Gi"
