apiVersion: v1
data:
    secret-key: ENC[AES256_GCM,data:6qz+KvhRhYtv93CUGaXNSRFNV7EyxG7SPnBS71SIV/WvCMB3UU9e22fYDwZdfTnRlxPr66ze9i6z92BL4jz2TBPnWUzY2UUkqfAr3bSTsq8r5s98Ika1uQ==,iv:kXAai87vlWrdeNO4ZudRm9/DtzzM2z2N2ieQGcplAbw=,tag:b7hlil/F2AU0mpXAfCFWzw==,type:str]
    vector-db-url: ENC[AES256_GCM,data:ecXO3yMzWR6PEtRyZDvgzdV0sdz1GBSwPRBJZs5DwYhhVbJcm6biZJvweymZkXdUCjp8fo6bu86CZ+QhN12dUyCqouokAjOJ0xEj5dpvSz8YxK+qwNGccTlNbpRbMu8T+a+g1mp42GZCUE6tPwbbf8TwxE/aklbFuZCut6CQfAzXtspVcAoqkhkIZ+Ze3+TzGJakOiJT1OdiO6ba,iv:+mk8rRho4hZgNzbN3/L4ryMg0G380mK7P2xInUaItbE=,tag:4u5F38mVUAAaY7g0rRCqxw==,type:str]
kind: Secret
metadata:
    name: open-webui-secrets
    namespace: open-webui
sops:
    age:
        - recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQXdIdFhSUkhxd1dBS3Bh
            dHF6NVRrMi9GeXdtQnhoMTUzTDM4NHBqOVFVCnVicllVL09Ba0xuOXE1RWk2a2ZR
            ZUFDM2g3VmE2M0VBNXMyZ2NTNkpKb2sKLS0tIDBBaUF6TG5xc1k0RmczMjFlRGRF
            c0dDT3pJeXZHUzdiY2FnY1VIaVJuNzQKtcBHTicVuHN5yeQBMB7DH1AywmQ6V+zY
            NJaDbT6fPm2LJItp8L1UPuNp1YvoKW5vBO/YU5qiAz0EI1hwXuQL8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T01:48:28Z"
    mac: ENC[AES256_GCM,data:Xu5a9eR8ociLvTzFsNe4dOfHwK8zGwHZrwUKK75gqn6B0fdJoqO39i8rk3leYY3fp7b+LjRXlKtaMCTJKmkorzuW4EPImL6NHsDVXRVJhjSUf5imWf8dbeXtxtGg5wF8fnfyx29oy9knZEDLB/mmbGgUWDjGqOMBwoU6zXyq9xI=,iv:r9UZG0SRQFGkx9JvmQ0/Reh8jjtHIICTXF9jwlR3CMw=,tag:Kj4w7xFs3LSIpAMuotuRPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
