apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: woodpecker
  namespace: woodpecker
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: woodpecker
    namespace: woodpecker
  values:
    agent:
      enabled: true
      replicaCount: 2
      persistence:
        enabled: false
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - woodpecker
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - agent
              topologyKey: kubernetes.io/hostname
      env:
        WOODPECKER_SERVER: woodpecker-server.woodpecker.svc.cluster.local:9000
        WOODPECKER_GRPC_KEEPALIVE_TIME: "90s"
        WOODPECKER_GRPC_KEEPALIVE_TIMEOUT: "20s"
      extraSecretNamesForEnvFrom:
        - woodpecker-shared
    server:
      enabled: true
      statefulSet:
        replicaCount: 2
        revisionHistoryLimit: 2
      updateStrategy:
        type: RollingUpdate
      persistence:
        enabled: true
        size: 10Gi
        storageClass: longhorn
        accessModes:
          - ReadWriteMany
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - woodpecker
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - server
              topologyKey: kubernetes.io/hostname
      env:
        WOODPECKER_HOST: https://woodpecker.cvsickle.com
        WOODPECKER_OPEN: false
        WOODPECKER_ADMIN: cvsickle
        WOODPECKER_GITHUB: true
        WOODPECKER_GRPC_KEEPALIVE_MIN_TIME: "5s"
        WOODPECKER_DATABASE_DRIVER: postgres
        DATABASE_USER:
          valueFrom:
            secretKeyRef:
              name: cnpg-woodpecker-auth
              key: username
        DATABASE_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: cnpg-woodpecker-auth
              key: password
        WOODPECKER_DATABASE_DATASOURCE: "postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@cnpg-cluster-rw.cnpg-system.svc.cluster.local:5432/woodpecker?sslmode=disable"
      extraSecretNamesForEnvFrom:
        - woodpecker-shared
        - woodpecker-github
