apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: woodpecker
  namespace: woodpecker
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: woodpecker
    namespace: woodpecker
  values:
    agent:
      enabled: true
      replicaCount: 2
      persistence:
        enabled: true
        size: 10Gi
        storageClass: longhorn
        accessModes:
          - ReadWriteMany
    server:
      enabled: true
      statefulSet:
        replicaCount: 2
        revisionHistoryLimit: 2
      updateStrategy:
        type: RollingUpdate
      persistence:
        enabled: true
        size: 10Gi
        storageClass: longhorn
        accessModes:
          - ReadWriteMany
      env:
        WOODPECKER_HOST: "https://woodpecker.cvsickle.com"
        WOODPECKER_OPEN: "false"
        WOODPECKER_ADMIN: "cvsickle"
        WOODPECKER_GITHUB: "true"
      extraSecretNamesForEnvFrom:
        - woodpecker-github
