apiVersion: v1
data:
    WOODPECKER_GITHUB_CLIENT: ENC[AES256_GCM,data:hde50jIOli81a0+yuhk/emm9o+KsSN502XXQEQ==,iv:tOvZ1W+XmK0sxgOCf3XnopQhSLddyqVOM7vqYEmZblE=,tag:WFefREw7GgdYPjcRE3GnQw==,type:str]
    WOODPECKER_GITHUB_SECRET: ENC[AES256_GCM,data:N1Nsw7O/7z+ZyiWSb+8fy1YXnOk+SgdmHx6GQuWFEgGKez73KK64fcCJdhDU9vC621QdsZVOsVY=,iv:VJ8Zx/GeMGRI5YVmr4t7rvfgHCN6J+FzvMGcb69lPIU=,tag:Oik8YEv5dul+J4xqvYQj/Q==,type:str]
kind: Secret
metadata:
    name: woodpecker-github
    namespace: woodpecker
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMDREV2NzZVpZb09MUTZS
            MDNCZk5hQnhSeTl3Ymo5MDBZWW5ET3hzSUc0CmdSMVc2c2g3cXlwN3YzUUEzWHhY
            VU1TbGhhem1hZm1LL0VZU0VOakdsclkKLS0tIE5pYzhvZXV2RytrV2hESTEwam5J
            MGcvOU9NTzljd3Zvakk1Q2hpbEQyZmcKBaXGIYmLyNd8Rk/eMYmttk4JQzdQHOfT
            X/w8J/GXbh+M03h2RoBZNgUg/17Po9g6lDoHNnnT1XfBJvo/uMmI5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T22:26:25Z"
    mac: ENC[AES256_GCM,data:2ttJ797lyhIa6NStfClJfh91MQ2FEZSGuoVFj6Ku+ft4gAy/cl7+mFaKS/Tmr0FlIXFiO53/iKpX1NoboC7YuiqM0zN/n/1HqIAu0eaJWzcGxRrkR8bTvmIdLGG+qzxMh5W787/nlgDjIOq1dy6cY85FfS4iIJhNFK9Gq9niVRI=,iv:5fBmGQfzL3vNTPNcizbHqD5IMajlBtRYRek4PwNtOFk=,tag:pNQJOINzb4cr7g4QTgx24A==,type:str]
    version: 3.13.1
