apiVersion: v1
data:
    WOODPECKER_AGENT_SECRET: ENC[AES256_GCM,data:nCeQuEMkVcJKRDl1GctlHzI89tWIrzMB0zBIgUgCJPYAMNKqRZKmvlITj74=,iv:QWvqTV3/7AD3fK4xoSCCbJ7xhqq/EWl/YoOB0Z7PSio=,tag:bYIO9k44qwqxPHfGaUjU7A==,type:str]
kind: Secret
metadata:
    name: woodpecker-shared
    namespace: woodpecker
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTFF2eGd3cFJkZVZFbHVi
            cE9rVGx0VnhnbXY3ZjVkMlorNkYyd0hJd1dJCmxnR25Wb0JrdEZtQngxZkFtbEcy
            RGw1V081amh3SjlMcTJEb290enI1NjAKLS0tIHVSTUJiRithdDZCTkdjdjZGKzhC
            bDI1MGl2MGdXZXBTbVp1YVNEK2hkV0UK0AC/tCO93RR8Gqf+Cq3h3yNhYhf7kw5L
            ZuVWrH/susVbK7SrH81Uv6by7vTMrni8gxN2ascI2qvF2/s+gZLx2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v59tukq0cvskn0ww9dwhh9z4ytgj03u599rtzs8xap83jtm8msssc9z8q7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T18:17:56Z"
    mac: ENC[AES256_GCM,data:RD637Jqn/cOQMtEMnxfy+BaH1xQJDREDqD9xoZsFcgFhP/YyrYDAMt8Z7bSBvdcdFBrxHrDbH46qHKMp2wnGIz3gtL8RivKFGni0vNIucSsvlAdOen+o2ukTfFyIM6BULKVPoDYS5dCVYZrh+nYSihaqqTHeCM8k6Zu+5F5XYgc=,iv:ga+uY+Z3FmlLYbJC4YtF1oFofiXmzaih4GAUn3BepUo=,tag:CQkV98xANdrHdIOuW4zQIA==,type:str]
    version: 3.13.1
